# Generated by Django 6.0.1 on 2026-02-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'in_progress'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='in_progress', max_length=11),
        ),
    ]
