# Generated by Django 6.0.1 on 2026-02-27 16:04

import auth_app.image_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=auth_app.image_helpers.profile_image_upload_path),
        ),
    ]
