# Generated by Django 6.0.1 on 2026-02-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0004_alter_offerpackage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
