# Generated by Django 6.0.1 on 2026-02-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers_app", "0005_alter_offer_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="revisions",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
