# Generated by Django 6.0.1 on 2026-02-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers_app", "0006_offer_revisions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="revisions",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
